# Generated by Django 6.0.5 on 2026-05-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_alter_product_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_num',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
